FROM php:8.2-fpm-alpine

RUN apk update && apk upgrade
RUN apk add nginx
RUN apk add --no-cache  --repository http://dl-cdn.alpinelinux.org/alpine/edge/community php
RUN  chmod 777 /var/www/html/

COPY ./index.php /var/www/html/index.php

ENTRYPOINT ["/usr/sbin/nginx", "-g", "daemon off;"]
EXPOSE 80