FROM alpine

RUN apk update 
RUN apk add nginx
RUN apk install php
RUN  chmod 777 /var/www/html/
RUN  touch /var/www/html/index.html

COPY quickstart.sh /
COPY ./index.php /var/www/html/index.php


ENTRYPOINT ["/quickstart.sh"]
CMD ["/usr/sbin/httpd","FOREGROUND"]
EXPOSE 80