apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deploymet
  labels:
    app: my-k8s-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-web-deploymet
  template:
    metadata:
      labels:
        app: my-web-deploymet
    spec:
      containers:
      - name: app-web
        image: adv4000/k8sphp:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-container-service
  labels:
    env: prod
    owner: Skliarov
spec:
  selector:
    app: myapp
  ports:
  - name: app-listener
    ptoco: tcp
    port: 80 # Port on Load Balancer
    targetPort: 8081 # Port on POD
