apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-multipod
  labels:
    app: my-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-web-deployment
  template:
    metadata:
      labels:
        app: my-web-deployment # Service will look for this PODS Labels!!!
    spec:
      containers:
        - name: app-web
          image: adv4000/k8sphp:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.25"
          ports:
          - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-container-service
  labels:
    env: prod
    owner: Skliarov
spec:
  selector:
    app: my-web-deployment # Select PODs with this label
  ports:
    - name: app-listener
      protocol: TCP
      port: 80 # Port on Load Balancer
      targetPort: 80 # Port on POD
  type: LoadBalancer