apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-deployment-multipod
  labels:
    app: my-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-multi-app
  template:
    metadata:
      labels:
        app: my-multi-app # Service will look for this PODS Labels!!!
    spec:
      containers:
        - name: my-web
          image: adv4000/k8sphp:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.25"
          ports:
          - containerPort: 80

        - name: app-web
          image: tomcat:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.25"
          ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-multi-container-service
  labels:
    env: prod
    owner: Skliarov
spec:
  selector:
    app: my-multi-app # Select PODs with this label
  ports:
    - name: my-web-listener
      protocol: TCP
      port: 80 # Port on Load Balancer
      targetPort: 80 # Port on POD

    - name: my-app-listener
      protocol: TCP
      port: 8080 # Port on Load Balancer
      targetPort: 8080 # Port on POD
  type: LoadBalancer