apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
    app: {{ .Release.Name }}-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app # Service will look for this PODS Labels!!!
    spec:
      containers:
        - name: {{ .Release.Name }}-web
          image: {{ .Values.container.image }}
          resources:
            limits:
              memory: "256Mi"
              cpu: "0.25"
          ports:
          - containerPort: 80