apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    name: web-app
    owner: sehii
spec:
  containers:
  - name: tomcat-container
    image: tomcat:latest
    ports:
    - containerPort: 8080
    resources:
      limits:
        cpu: "0.5" # 0.5 CPU cores
        memory: "512Mi" # 512 megabytes
      requests:
        cpu: "0.25" # 0.25 CPU cores
        memory: "256Mi" # 256 megabytes
  - name: apache-container
    image: httpd:latest
    ports:
    - containerPort: 80
    resources:
      limits:
        cpu: "0.5" # 0.5 CPU cores
        memory: "256Mi" # 256 megabytes
      requests:
        cpu: "0.25" # 0.25 CPU cores
        memory: "128Mi" # 128 megabytes