apiVersion: v1
kind: Pod
metadata:
  name: web-app
  labels:
    name: web-app
    owner: sehii
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80